# Generated by Django 3.2.11 on 2022-03-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('confirm_password', models.CharField(max_length=15)),
                ('hint_question', models.CharField(choices=[('first school name', 'First School Name'), ('pet name', 'Pet Name'), ('teacher name', 'Teacher Name'), ('favorate food', 'Favorate Food'), ('collage name', 'Collage Name')], max_length=30)),
            ],
        ),
    ]
