# Generated by Django 3.2.11 on 2022-06-11 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveTextDocs',
            fields=[
                ('file_name', models.CharField(blank=True, max_length=30, null=True)),
                ('createdAt', models.DateTimeField()),
                ('updateAt', models.DateTimeField()),
                ('docId', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('fileData', models.TextField(blank=True, null=True)),
                ('userId', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='registration.userregistration')),
            ],
        ),
    ]
